### ISSUE TITLE
Extension of `GraphDCEL` with general graph functions

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/graph-algo-ptas#34]
- [x] Number of vertexes of the whole graph
- [x] the number of neighbours of a vertex
- [x] neighbors fn
- [x] The number of edges e
- [x] The number of faces f
- [x] the number of vertices of a specific face

**Comment by pdrtzk** [comment]
Perhaps it would be useful to implement the function 'neighbors' function as part of `GraphDCEL` as well.
Currently we have implemented it ourselves in [src/algorithm/spantree.rs](https://github.com/thm-mni-ii/graph-algo-ptas/blob/i27-Implement-Tree-Decomposition/src/algorithm/spantree.rs).

**Comment by pdrtzk** [comment]
More (Nice-to-Have, but no Must-Have):

- [ ] The number of edges e
- [ ] The number of faces f

=> So you can compute Euler's formula wth the number of nodes n: _n-e+f=2_.

**Comment by pdrtzk** [comment]
I could really use the number of vertices of a specific face. Does a method like this make sense?

**Comment by mxsph** [comment]
> I could really use the number of vertices of a specific face. Does a method like this make sense?

Wenn you need it, it make sence 😅. I added it to the list 👍.
