### ISSUE TITLE
Scout Rust graph libraries

### ISSUE THREAD

**Issue by snicki13** [thm-mni-ii/graph-algo-ptas#6]
Look for graph libraries to be used as an addition to self-implemented data structures or basic algorithms.

**Comment by Zitrone44** [comment]
* https://github.com/petgraph/petgraph
  * https://crates.io/crates/daggy
  * https://github.com/sebschmi/abstract-datastructures-rs
  * https://github.com/sebschmi/bigraph-rs
* https://chiselapp.com/user/fifr/repository/rs-graph/doc/release/README.md
* https://github.com/purpleprotocol/graphlib
* https://github.com/yamafaktory/hypergraph
